# Generated by Django 2.0.2 on 2018-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id',
                 models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='reminder_id')),
                ('user_id', models.CharField(max_length=1024, verbose_name='user_id')),
                ('chat_id', models.CharField(max_length=1024, verbose_name='chat_id')),
                ('text', models.CharField(max_length=1024, verbose_name='text')),
                ('when', models.DateTimeField(verbose_name='when')),
            ],
        ),
    ]
